### PR TITLE
#216-bug-프로필-수정-모달-ui-문제

### LINKED ISSUE #216: [Bug] 프로필 수정 모달 UI 문제
# Describe the bug

프로필 수정 모달에서 정렬되지 않은 문제가 있습니다. (별명)
추가적으로 별명이 잘려서 표시되는 문제도 있습니다. (`...`으로 표시, width를 늘리기 등의 옵션 논의 필요)

# Screenshots

KakaoTalk_20220829_232434907

### PR DESCRIPTION
**Pull request by 0ev**
# Summary 

It closes #216 

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 
image

# Further Work 

- Do something...

### CODE REVIEW

File: src/components/Mypage/PopupMypage/PopupMypage.jsx [hunk 1]
```diff
@@ -180,6 +182,7 @@ const PopupMypage = (props) => {
   const styleLay1 = {
     position: "relative",
     display: "flex",
+    alignItems: "center",
```
Comment (GrasshopperBears) [inline src/components/Mypage/PopupMypage/PopupMypage.jsx:185]: ❤️

**Review by GrasshopperBears — APPROVED** [review]
