### PR TITLE
Fix: Issue solved

### LINKED ISSUE #780: #773의 버그 : 참여 중인 방 버튼이 비활성화 되는 경우
packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
버튼이 비활성화 되는 다른 검사에 걸리면 (예: 이미 5개 방에 참여 중임) 참여 중인 방 바로가기 버튼도 비활성화되는 상황입니다. isAlreadyPart면 어떤 경우에도 버튼이 활성화되도록 수정하겠습니다.

### PR DESCRIPTION
**Pull request by jinhyeonkwon**
# Summary 

It closes #780 (#773 의 오류)

### CODE REVIEW

**Review by jyjy1229 — APPROVED** [review]

**Comment by ybmin** [comment]
LGTM 👍

File: packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx [hunk 1]
```diff
@@ -210,7 +210,7 @@ const BodyRoomSelection = ({ roomInfo }: BodyRoomSelectionProps) => {
       {isLogin || isRoomFull || isDepart ? (
         <Button
           type="purple"
-          disabled={isRoomFull || (isDepart && !isAlreadyPart) || isMaxPart}
+          disabled={(isRoomFull || isDepart || isMaxPart) && !isAlreadyPart}
```
Comment (ybmin) [inline packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx:213]: LGTM 👍

**Review by ybmin — APPROVED** [review]
