### PR TITLE
#134 Fix style of pages and Refactor

### LINKED ISSUE #134: 스타일 수정 및 리팩토링
# Summary 

피그마와 맞지 않는 스타일들을 수정합니다. 또한 비효율적으로 사용되던 요소들의 리팩토링도 진행합니다.

# Tasks 

- [x] 개설 페이지 : 옵션들
- [x] 내 방 페이지 : 방 아이템 Hover
- [x] 마이 페이지 : 컨테이너 내부 스타일
- [x] 리팩토링 : 방 리스트를 RoomList로 컴포넌트화
- [x] 리팩토링 : 아이콘

### PR DESCRIPTION
**Pull request by imYourChoi**
# Summary 

It closes #134

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? n

# Images 

# Further Work 

- Do something...

### CODE REVIEW

File: src/components/Search/AddRoom/AddRoom.jsx [hunk 1]
```diff
@@ -56,25 +56,23 @@ const AddRoom = (props) => {
         ),
       });
       if (result.status === 200) {
-        alert("방이 개설됨!!");
+        history.push("/myroom");
       } else {
-        console.log("add room error");
+        alert("add room error");
```
Comment (14KGun) [inline src/components/Search/AddRoom/AddRoom.jsx:61]: 에러 상황에서 alert를 하는 것이 맞을까요???
관련 논의가 필요할 듯 합니다.

File: src/components/MyPage/MyPage.jsx [hunk 2]
```diff
@@ -90,114 +102,100 @@ const Setting = () => {
...
           사용 약관 및 개인정보 보호 규칙
         </BtnC>
-        <BtnC img={SparcsLogoBlack} onClick={() => setOpen1(true)}>
-          만든 사람들
-        </BtnC>
-        <BtnC
-          img={(style) => <ExitToAppRoundedIcon style={style} />}
-          onClick={handleLogout}
-        >
+        <BtnC icon="logo">만든 사람들</BtnC>
```
Comment (14KGun) [inline src/components/MyPage/MyPage.jsx:183]: onClick을 넘겨줘야 할 것 같아요!

**Review by 14KGun — CHANGES_REQUESTED** [review]

**Review by 14KGun — APPROVED** [review]

**Review by 14KGun — APPROVED** [review]
